### ISSUE TITLE
Debugger

### ISSUE THREAD

**Issue by yitzchak** [robert-dodier/maxima-jupyter#102]
This is informational only. The git version of common-lisp-jupyter now has a debugger with breakpoints and stepping. I am working on adding maxima support.

![Screenshot from 2021-08-08 14-38-03](https://user-images.githubusercontent.com/1247961/129491496-d5a7e985-1e47-4a5c-b850-69c56f239f29.png)

![step](https://user-images.githubusercontent.com/1247961/129491470-94c7b836-63ad-4340-a79d-5fa772e48cc9.gif)

**Comment by robert-dodier** [comment]
Terrific, thanks a lot for working on it.

**Comment by yitzchak** [comment]
Breakpoints and stepping is still a bit wonky, but you can see some stepping and line tracking (some) going on here.

![maxima-step](https://user-images.githubusercontent.com/1247961/130231086-e48479e8-c41f-408b-badf-4a84db0e08be.gif)

**Comment by yitzchak** [comment]
Stepping with breakpoints and line tracking working!

![stepping](https://user-images.githubusercontent.com/1247961/130289820-d784f8fa-21c0-4c56-b43c-954f78b4a883.gif)

**Comment by robert-dodier** [comment]
Wow, really amazing, great work Tarn!

**Comment by yitzchak** [comment]
Thanks Robert!
