### ISSUE TITLE
"makelist() $" still printing an output

### ISSUE THREAD

**Issue by CdeMills** [robert-dodier/maxima-jupyter#109]
Hello,
in a Jupyter notebook, the following line generates some output:
[Input 1] mylist: makelist(j*j, j, 1, 4)$
[Output 1] [1, 4, 9, 16]

while in maxima-console or xmaxima, this is not the case. Up to now, I only saw this with "makelist". Is it possible to avoid displaying its output ?

Regards

Pascal

**Comment by robert-dodier** [comment]
Hi Pascal, is it only `makelist` or is it that all `$` inputs display the result?

A work-around is to enter `(makelist(...), 0) $` so that if the result is displayed, it's only `0`. I know that's clumsy.

**Comment by CdeMills** [comment]
Hello Robert,
all the $ lines display their result. That's really annoying for 'makelist' returning long list. Your fix avoids this issues.

Thank you

Regards

Pascal

**Comment by yitzchak** [comment]
I probably broke this in the debugging PR. Looking now.

**Comment by yitzchak** [comment]
Fix found. PR submitted.

**Comment by robert-dodier** [comment]
I've merged the PR. Thanks Tarn!

**Comment by yitzchak** [comment]
Awesome. Thanks Robert.

**Comment by CdeMills** [comment]
I confirm this fix is working. Thank you all.

Pascal
