### ISSUE TITLE
colab-maxima-bootstrap

### ISSUE THREAD

**Issue by ng0177** [robert-dodier/maxima-jupyter#116]
Intrigued by [julia](https://github.com/johnnychen94/colab-julia-bootstrap), I wonder if there is a way to go similar colab wise w/ maxima.

Call it a feature request. Thank you!

**Comment by yitzchak** [comment]
With the magic commands I suppose anything is possible. In that past I attempted here yitzchak/common-lisp-jupyter#35

Personally, Colab seems like a waste of time. I'm not really sure what you get with it that you don't get by just installing your own Jupyter Lab server, etc.

**Comment by ng0177** [comment]
Good thinking, you are actually right. It is better to spend the time on installing a local Jypter server at the other end.
