### ISSUE TITLE
Race condition with gnuplot_pipes 

### ISSUE THREAD

**Issue by mrohne** [robert-dodier/maxima-jupyter#122]
Examples using ```plot2d``` results in ```examples/Plots.ipynb```  not working.

Observations:
The (default) ```gnuplot_pipes``` driver has no provision for maxima to wait for the plotting to finish. At the time of ```MAXIMA-JUPYTER::PLOT-P```  the plot file is not even there (no plot shown), or the plot file is incomplete during ```MAXIMA::JUPYTER-FILE```  (broken plot icon shown).

Platforms:
- Linux
- MacOS
- Chrome OS

Workaround:
Use ```set_plot_option([plot_format,gnuplot])$```

**Comment by robert-dodier** [comment]
Thanks for your comment. From what you were saying, it makes sense to set the default `plot_format` to `gnuplot` instead of `gnuplot_pipes`. Does that sound right to you? If so, I will commit that change. @yitzchak Do you foresee any complications if `plot_format` is changed?

**Comment by mrohne** [comment]
Thank you for looking into this!
I agree, setting plot_options to gnuplot seems to work on the systems I
have access to.

Ole

**Comment by yitzchak** [comment]
Sounds good to me.

**Comment by robert-dodier** [comment]
Hmm, I am having trouble creating an embedded plot. I am working on Ubuntu 16.04 + SBCL 2.3.7 + Maxima post-5.47, with "loaded by Quicklisp" installation method. I launched the notebook. When I tried a `plot2d` example, I got a separate Gnuplot window, but I expected the image to be embedded in the notebook. I also tried `set_plot_option ([svg_file, "tmpfooplot.svg"]);` and then `plot2d` again, but it just returns the name of the SVG file. I tried `set_plot_option ([plot_format, gnuplot]);`, and then `plot2d` again, now it returns the name of the Gnuplot output file and the name of the SVG file. Not sure what to try at this point.

It is a bit embarassing, but I don't remember how to enable embedded plot images; can someone @mrohne @yitzchak  remind me? Thanks for your help.

**Comment by mrohne** [comment]
Sorry I forgot about this:
In stock Maxima, gnuplot and gnuplot_pipes disagree about what return value
to pass from plot2d. I had patched the gnuplot-driver to match
gnuplot_pipes and only return the plot file, which is what maxima-jupyter
expects.
In the end I'm afraid there is no user-level workaround here.
Ole

**Comment by robert-dodier** [comment]
What is your patch for gnuplot-driver? I have been trying some different modifications and I can't seem to find something that works. I'll be interested to see what you did.

**Comment by yitzchak** [comment]
I am thinking we just need to look at the plot options in the plot2d override in order to decide what to do. We do something like that in implicit_plot already.

https://github.com/robert-dodier/maxima-jupyter/blob/f12f6ef977778db717844c7332ba374d555758e9/src/overrides.lisp#L116-L120

**Comment by yitzchak** [comment]
Also, in the gnuplot_pipes situation we could spawn a thread to wait on the result and then just use Jupyter display messages versus relying on the return value.

**Comment by mrohne** [comment]
Sorry I missed this.. Essentially I copied the return logic from gnuplot_pipes (below).

Ole
diff --git a/src/gnuplot_def.lisp b/src/gnuplot_def.lisp
index 80c174bd5..4e08d7ce2 100644
--- a/src/gnuplot_def.lisp
+++ b/src/gnuplot_def.lisp
@@ -725,7 +725,8 @@
                          :direction :output :if-exists :supersede)
           (format fl "~a" (slot-value plot 'data)))
         (gnuplot-process options file output-file)
-        (cons '(mlist) (cons file output-file))))
+        (when output-file
+          (cons '(mlist) output-file))))
      ($gnuplot_pipes
       (send-gnuplot-command (slot-value plot 'data))
       (when output-file

**Comment by mrohne** [comment]
> @mrohne I have merged a PR from Tarn Burton (commit [e20fdd7](https://github.com/robert-dodier/maxima-jupyter/commit/e20fdd7a14d912c02255f47ff6e7b4287e0d1e82)) which is intended to fix this issue. Ole, can I ask you to try the new version and verify whether it works for you?

I confirm this patch works, assuming ```set_plot_option([plot_format,gnuplot])$```

**Comment by robert-dodier** [comment]
Ole, thanks for the update, sounds good.

@yitzchak What do you think about making `gnuplot` the default `plot_format`? I guess I am thinking that could be helpful, since otherwise people might run into the same race condition, which has a non-obvious workaround.

**Comment by yitzchak** [comment]
I think that is a good idea. I don't think the gnuplot_pipes method was really designed to output files synchronously.
