### ISSUE TITLE
Install dependencies before first use?

### ISSUE THREAD

**Issue by sdwfrost** [robert-dodier/maxima-jupyter#38]
I've been having issues with using maxima-jupyter in Binder, due to the installation of dependencies on the first use; this slows down the launch of the notebook, sometimes leading to a timeout. Is it possible to install the dependencies via quicklisp separately on the command line to avoid this problem?

**Comment by robert-dodier** [comment]
Hi, thanks for your interest in Maxima-Jupyter. What installation method are you using? Did you create a binary image containing Maxima + maxima-jupyter? Or are you loading maxima-jupyter each time Maxima is launched?

I think if you use the method of creating a binary image containing Maxima + maxima-jupyter, dependencies will be loaded by Quicklisp only once. This method is described in `Readme.md` in the section "Quick Install" where it says "There are two kernel installation techniques. The first is to create a saved
image as detailed in make-maxima-jupyter-recipe.txt."

**Comment by robert-dodier** [comment]
I'm closing this issue, but if you are still having a problem feel free to reopen it or create a new one. I think the method of creating a binary image is probably the best way forward here, since the whole purpose is to create a binary which contains all the required stuff in it.
