### ISSUE TITLE
getting proper maxima/SBCL version

### ISSUE THREAD

**Issue by szazs89** [robert-dodier/maxima-jupyter#42]
AFA I understand from the `Readme.md`, there are two ways to install _maxima-jupyter_, and it seems to me that the first method is preferred. Thus, I tried to do according to it:
(since I use _debian-buster_ I have also tried to get the appropriate packages which I was able to found)

1. I need maxima with appropriate lisp: the buster repo contains only maxima-sage with ECL (5.41.0), however, I had no success with it
2. therefore I downloaded the debs of `maxima-sbcl` and `maxima-common` (5.42.0) from sourceforge.net and installed them
3. I did also `apt install sbcl` (1.4.13) and then I tried to follow `make-maxima-jupyter-recipe.txt`, i.e.
```
# cd /opt/src/maxima-jupyter
# mkdir -p binary/binary-sbcl
# maxima -l sbcl
Maxima 5.42.0 http://maxima.sourceforge.net
using Lisp SBCL 1.4.10.debian
[...]
(%i1) :lisp (load "load-maxima-jupyter.lisp")
While evaluating the form starting at line 1, column 0

Maxima encountered a Lisp error:

 #<SB-SYS:FD-STREAM for "file /usr/lib/sbcl/contrib/asdf.fasl" {1002F9ED53}> is
 a fasl file compiled with SBCL 1.4.13.debian, and can't be loaded into SBCL
 1.4.10.debian.

Automatically continuing.
(%i1) :lisp (sb-ext:save-lisp-and-die #P"binary/binary-sbcl/maxima-jupyter-exec" :executable t :toplevel 'maxima-jupyter:kernel-start-exec)

Maxima encountered a Lisp error:

 Package MAXIMA-JUPYTER does not exist.

   Line: 1, Column: 132, File-Position: 132

   Stream: #<SB-IMPL::STRING-INPUT-STREAM {1002FA9C33}>

Automatically continuing.
```

So, there might be an SBCL version mismatch, and MAXIMA-JUPYTER package does not exist...(?)

What did I miss?
Zsolt

**Comment by robert-dodier** [comment]
Zsolt, the crucial part of the error seems to be:

#<SB-SYS:FD-STREAM for "file /usr/lib/sbcl/contrib/asdf.fasl" {1002F9ED53}> is
 a fasl file compiled with SBCL 1.4.13.debian, and can't be loaded into SBCL
 1.4.10.debian.

The Maxima banner reports it was complied with SBCL 1.4.10.debian, while 1.4.13 is installed on your system. So the compiled file asdf.fasl which belongs to 1.4.13 isn't understood by 1.4.10.

I see a couple of options. One is to install 1.4.10 for your system, which, I guess, means a downgrade instead of an upgrade. I don't know if there is an installable package for 1.4.10 for your system; if not, then you can consider compiling SBCL. I have compiled SBCL and it is not too hard, just follow the readme instructions, as I recall.

The other I see is that you can compile Maxima, which is not a big deal. You need to obtain a Maxima tarball, from http://sourceforge.net/projects/maxima/files/. After unpacking the tarball, cd to top level directory and then say:

./configure --enable-sbcl
make
sudo make install

Hope this helps,
Robert

**Comment by szazs89** [comment]
OK.
1. purged maxima-sbcl and maxima-common, and downloaded the source.
2. uninstalled the local sbcl and `apt install sbcl` (1.4.13.debian)
3. build maxima (5.42.1) as you suggested and installed locally (/usr/local)

Then as a regular user installed _quicklisp_ as given in `/usr/share/doc/cl-quicklisp/README.Debian` and evaluated the recommended commands (creating .sbclrc, etc.). Afterwards
```
$ cp -a /opt/src/maxima-jupyter /tmp/maxima-jupyter
$ cd /tmp/maxima-jupyter
$ mkdir -p binary/binary-sbcl
$ maxima -l sbcl
Maxima 5.42.1 http://maxima.sourceforge.net
using Lisp SBCL 1.4.13.debian
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) :lisp (load "load-maxima-jupyter.lisp")
now ASDF:*CENTRAL-REGISTRY*=("/tmp/maxima-jupyter/src/")
STYLE-WARNING:
   Character decoding error in a #|-comment at position 1016 reading source stream #<FORM-TRACKING-STREAM for "file /usr/local/share/maxima/5.42.1/share/stringproc/cryptools.lisp" {1005B820F3}>, resyncing.
[...]
; Loading "maxima-jupyter"
[package fredokun-utilities]......................
[package maxima-jupyter].............
(%i1) :lisp (sb-ext:save-lisp-and-die #P"binary/binary-sbcl/maxima-jupyter-exec" :executable t :toplevel 'maxima-jupyter:kernel-start-exec)
$ ls  binary/binary-sbcl/       
maxima-jupyter-exec
```
So, the executable was created. Then as root
```
# cd /tmp/maxima-jupyter
# cp -a binary/binary-sbcl/maxima-jupyter-exec /usr/local/bin
# python3 ./install-maxima-jupyter.py --exec=/usr/local/bin/maxima-jupyter-exec
```
which created `/usr/local/share/jupyter/kernel/maxima/kernel.json` appropriately, except that the folder `/usr/local/share/jupyter/kernel/maxima` is not world readable. So, a
```
chmod 755 /usr/local/share/jupyter/kernel/maxima
```
is necessary.
After restarting jupyter(lab) the extension seems to work fine. (I am curious whether it can handle inline plots... but that will be another issue.)
Thanks Robert!

**Comment by robert-dodier** [comment]
Hi Szolt, glad to hear you got it working. I'll close this issue now but feel free to open another.

About /usr/local/share/jupyter/kernel/maxima not being world-writeable, you can also say --user on the install-maxima-jupyter.py command line, and the kernel.json will be written to a directory somewhere under your home directory.

About the character decoding error in cryptools.lisp, I don't know what's going on there. cryptools.lisp contains some non-ASCII UTF-8 characters, but that shouldn't be a problem for SBCL. I inspected crytools.lisp via `od -A d -c` and looked at character 1016 but it doesn't seem to be anything unusual (it's just ASCII text around there).

Have fun with maxima-jupyter and keep us posted!

**Comment by defencedog** [comment]
@szazs89 Sorry to bumb an old thread but my `maxima` is unable to locate `asdf` while loading it in `sbcl` is no problem. Kindly share your `.sbclrc` contents

_~ $ maxima -l sbcl
Maxima 5.47.0 https://maxima.sourceforge.io
using Lisp SBCL 2.3.3
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information._

**Comment by robert-dodier** [comment]
@defencedog I have some ideas about that, but can I ask you to open a new ticket to discuss it? It seems to be a separate issue from the original topic of this thread.

All the best,

Robert
