### ISSUE TITLE
Running this repo on Binderhub

### ISSUE THREAD

**Issue by psychemedia** [robert-dodier/maxima-jupyter#43]
I've tried a couple of times (unsuccessfully) to get the `maxima-jupyter` kernel running via a Docker build, but I wonder if it would make more sense to add requirements files (`apt.txt` for Linux packages, `postBuild` for running commands once all package requirements are in place)) to this repo so that it can be run on [MyBinder](https://mybinder.org) ([docs](https://binderhub.readthedocs.io/en/latest/))?

There are a couple of immediate benefits to this:

1. People can try out the kernel directly without having to install anything.
2. The repo can also be used as a target for running the kernel in a local Jupyter notebook server using  [`repo2docker`](https://repo2docker.readthedocs.io/en/latest/).

There is also a tertiary benefit in that Binderised kernels can be called from arbitrary webpages. This would allow `maxima` code to be written into a form on a webpage, executed against a dynamically launched kernel running on MyBinder, and with any response embedded back in the webpage. There's an example using a *Gnuplot* kernel [here](https://blog.ouseful.info/2018/12/06/jupyter-is-not-just-notebooks/).

**Comment by robert-dodier** [comment]
Tony, I think that makes a lot of sense, but unfortunately I can't promise to work on that. Is that something you want to work on? If so I encourage you to go ahead, I'll be glad to incorporate patches or pull requests as you see fit.

**Comment by psychemedia** [comment]
@robert-dodier I made a quick attempt yesterday but didn't get very far. I've not had success with running the Dockerised `maxima-jupyter` kernels either. The whole Lisp thing, environments etc are alien to me, so even trying to figure out the simplest things takes time... I'll try to have another go when I get a chance... (Use context is that folk I know use Maxima in a course and are thinking about migrating to notebooks, but they want to keep on using Maxima. I was hoping to be able to run an off-the-shelf demo to show them how it might look... I'll see if they can help me get a build script running...)

**Comment by robert-dodier** [comment]
What platform are those folks using? If they are using Windows, I'm not sure what's involved in getting maxima-jupyter to run; I don't have a Windows system available to work on. But for Linux, I'm pretty sure that I've figured out how to get a working maxima-jupyter setup in a straightforward, consistent way, and we might be able to relatively easily construct a binary .deb package. (Linux + .deb or .rpm packages is what I'm familiar with -- Docker is new to me.) For MacOS, might be somewhere between Windows and Linux.

**Comment by psychemedia** [comment]
I'm guessing Windows...

If you have a Linux set-up that works from scripts, it should be easy enough (?!) to add the config files to this repo that would allow it to run using MyBinder ([docs](https://mybinder.readthedocs.io/en/latest/)).  The build process automatically inserts a Jupyter notebook server into the built image and automatically launches it when you "run" a repo on MyBinder.

Any required Linux packages listed in an `apt.txt` file are automatically installed, as are any required Python pip packages listed in `requirements.txt`. A `postBuild` file contains Linux command line commands that are to be run once the packages are installed.

For example, in [this repo](https://github.com/ouseful-PR/gnuplot_kernel/tree/Binderise) that builds a gnuplot kernel using metakernel, the build process:

- uses a default Jupyter notebook server setup;
- installs `gnuplot` from `apt.txt`;
- installs `matplotlib` and `numpy` from `requirements.txt`;
- builds the kernel from automatically running the `setup.py` file;
- uses the `postBuild` file to add the kernel to the automatically installed notebook server's list of available kernels (`python -m gnuplot_kernel install --user`).

See other examples of Binder configs here: https://github.com/binder-examples .

One advantage of "binderising" the repo in this way is it lets folk try the kernel out at the click of a button via MyBinder; a second advantage is that they could also run it in a local docker container by simply firing off the command: `jupyter repo2docker https://github.com/robert-dodier/maxima-jupyter` on their own computer, assuming it's running docker.

**Comment by robert-dodier** [comment]
Thanks for the info about MyBinder. I think its feasible to binderify the maxima-jupyter installation process. The process requires a few shell commands (e.g. ./configure, make, make install to compile Maxima). How can we handle shell commands in MyBinder? Thanks for the info, I appreciate it.

**Comment by psychemedia** [comment]
Shell commands can be run via the `postBuild` file after installs using `apt.txt` and `requirements.txt` or `environment.yml`. MyBinder actually uses `repo2docker` underneath so [those docs](https://repo2docker.readthedocs.io/en/latest/config_files.html) provide more details about the naming / expected contents of config files. You can also go off-piste with a Dockerfile ([docs](https://mybinder.readthedocs.io/en/latest/tutorials/dockerfile.html)).

**Comment by robert-dodier** [comment]
Hi Tarn, thanks a lot for working on the Dockerfile for Maxima. Seems to work as expected (except for plots as you noted) when I try the link you posted. Great work, I think this will help others a lot.

**Comment by yitzchak** [comment]
Thanks for trying it out, Robert. Plots should work now. I'm try to get code highlighting to work next.

**Comment by robert-dodier** [comment]
PR #45 resolves this issue.
