### ISSUE TITLE
*tex-environment-default* $$ -> \[ for correct pdf generation through pdfLaTeX. 

### ISSUE THREAD

**Issue by ymei** [robert-dodier/maxima-jupyter#48]
Suggest to add the following into `load-maxima-jupyter.lisp`:
```
(setq *tex-environment-default* '("\\[" . "\\]"))
```

The default delineator $$ for TeX cannot have \tag{} inside, which causes pdfLaTeX to complain.  Changing $$ to \\[,\\] pair solves this problem.  The use of $$ to delineate equations in LaTeX is not advised anyway.

**Comment by efferre79** [comment]
I am facing the same problem here
