### ISSUE TITLE
Maxima Syntax Highlighting hangs when '$' is entered

### ISSUE THREAD

**Issue by WetHat** [robert-dodier/maxima-jupyter#68]
Hi Robert,
I'm running the Maxima kernel on Windows 10 with Chrome. I've successfully installed the Maxima syntax highlighting into `notebook/static/components/codemirror/mode/maxima`, but it never worked for existing notebooks using the `maxima-jupyter` kernel. No highlighting would be shown at all. On fresh notebooks it would work until a '$' was entered into a code cell. Upon entering '$' the code cell would hang and no more input was possible. Since I really would like to have this feature I did some debugging and found that the javascript debugger shows this codemirror exception when '$' is entered: 

~~~
Exception in event handler for select.Cell Error: Mode maxima failed to advance stream.
    at readToken (main.min.js:1732)
    at runMode (main.min.js:1786)
    at highlightLine (main.min.js:1632)
    at getLineStyles (main.min.js:1676)
    at buildLineContent (main.min.js:1922)
    at getLineContent (main.min.js:2300)
    at buildLineElement (main.min.js:2381)
    ...
~~~

Codemirror makes heavy use of regular expressions, so I figured that `$` would probably cause some trouble since it is a special character.

After some experimentation I came up with this hack in `maxima.js` line 60:

~~~ Javascript
if (ch === '$') {
    return 'punctuation';
}
~~~

Here's a patch for that:
[dollar.patch.txt](https://github.com/robert-dodier/maxima-jupyter/files/3641351/dollar.patch.txt)

With this hack Maxima syntax highlighting just works fine for new and existing Jupyter notebooks. Maybe this helps you finding a proper fix.

WetHat

**Comment by robert-dodier** [comment]
Hi, that makes sense to me. I'd be glad to accept a pull request for this, can I ask you to create a PR? It's OK if you don't want to, you can let me know.

**Comment by WetHat** [comment]
I think I can clone the repo and send you a pull request.
WetHat

**Comment by robert-dodier** [comment]
Just cleaning up this ticket. The PR was merged so I'll close the ticket now.
