### ISSUE TITLE
expressions are apparently evaluated twice

### ISSUE THREAD

**Issue by robert-dodier** [robert-dodier/maxima-jupyter#7]
It seems like expressions are evaluated twice. A first guess is that the result of evaluation is itself being evaluated. I could probably devise a test to determine if that's really the case.

E.g. given input `[A,B,C,D]:'[B,C,D,E]`, I expect the output should be `[B, C, D, E]` (as it is in the Maxima command line interface), but instead I get `[C,D,E,E]`. At this point, given input `values`, I expect to get `[A, B, C, D]` (as it is in command line Maxima) but I get `[B,C,D,E]` instead.

**Comment by yitzchak** [comment]
@robert-dodier I have reproduced this. There is an `meval` in `tex`. One possible fix is to use `tex1` instead.
