### ISSUE TITLE
very minor typo in jupyter maxima build instructions

### ISSUE THREAD

**Issue by powerline332** [robert-dodier/maxima-jupyter#76]
Hello, just in case someone gets stuck here, `--user` is an install option for pip(3) and so the order should be changed.

Additionally, I could not get the new method to work, but the old method - `old method, 1.) user` did work for me.

 inxi -v 2
System:    Kernel: 5.0.0-37-generic x86_64 bits: 64 Desktop: Cinnamon 4.4.8 
           Distro: Linux Mint 19.3 Tricia 
Machine:   Type: Laptop System: Apple product: MacBookPro11,3 v: 1.0 serial: <root required> 
           Mobo: Apple model: Mac-2BD1B31983FE1663 v: MacBookPro11,3 serial: <root required> 
           UEFI: Apple v: MBP112.88Z.0146.B00.1804111138 date: 04/11/2018 
CPU:       Quad Core: Intel Core i7-4980HQ type: MT MCP speed: 798 MHz min/max: 800/4000 MHz 
Graphics:  Device-1: NVIDIA GK107M [GeForce GT 750M Mac Edition] driver: nvidia v: 390.116 
           Display: x11 server: X.Org 1.19.6 driver: nvidia unloaded: fbdev,modesetting,vesa 
           resolution: 2880x1800~60Hz 
           OpenGL: renderer: GeForce GT 750M/PCIe/SSE2 v: 4.6.0 NVIDIA 390.116 

 maxima
Maxima branch_5_43_base_272_gbba3e0cbc http://maxima.sourceforge.net
using Lisp SBCL 2.0.1-dirty
Distributed under the GNU Public License. See the file COPYING.
Dedicated to the memory of William Schelter.
The function bug_report() provides bug reporting information.
(%i1) build_info();
(%o1) 
Maxima version: "branch_5_43_base_272_gbba3e0cbc"
Maxima build date: "2020-01-26 18:18:55"
Host type: "x86_64-pc-linux-gnu"
Lisp implementation type: "SBCL"
Lisp implementation version: "2.0.1-dirty"
User dir: "/home/sbh/.maxima"
Temp dir: "/tmp"
Object dir: "/home/sbh/.maxima/binary/branch_5_43_base_272_gbba3e0cbc/sbcl/2_0_1_dirty"

After installing SBCL, then Maxima (both from Git), I then installed Quicklisp and got the emacs/slime environment working. Then I tried the Maxima/Jupyter and somewhere along the way, something clobbered my SBCL (I didn't research it at all), as I could no longer call it - complained of missing core.  

Anyways, did it all over again with the old method and it works fine.

Thank you for your work!

**Comment by robert-dodier** [comment]
I'm going to go over all the readme stuff and update it. I'll be sure to verify the options for the commands.
