### ISSUE TITLE
How to build with an existing python3 and jupyter / jupyterhub setup?

### ISSUE THREAD

**Issue by sirgogo** [robert-dodier/maxima-jupyter#8]
Hi, I was wondering if you could provide a little more instruction as to how to build the maxima / CL-jupyter lisp image? I have never used lisp before, so I think the concept may be foreign to me.

I have a working jupyterhub and python setup. It would be great if there was a way to download/build this maxima plugin for use in notebooks. Sorry in advance if I am being unclear. 

hanks.

**Comment by robert-dodier** [comment]
Hi, did you see the file make-maxima-jupyter-recipe.txt ? That file
contains instructions that can be typed into a Maxima session to create the
maxima-jupyter plugin.

To clarify what's going on, in Lisp systems it is easy to create an image
of the Lisp interpreter plus additional code which has been loaded into the
interpreter. So it's easy to incrementally extend a Lisp program -- just
load some more code and save the resulting image. That's how the
maxima-jupyter plugin is created -- Maxima itself is a Lisp image, so we
load some more functions for the Jupyter stuff, and save the image. I guess
it would be helpful if I would put this explanation into the notes.

Let me know if you need something more. Thanks for your interest in
Maxima-jupyter, I'm glad someone wants to use it!

best,
Robert Dodier

**Comment by sirgogo** [comment]
Okay I see! Thanks for the clarification. Any idea where I could get a Clozure CL maxima binary? (Sorry I'm pretty un-knowledgable, but I see some binaries listed here: http://maxima.sourceforge.net/download.html )

**Comment by robert-dodier** [comment]
I don't know of anybody who is building Clozure CL binaries, so you will
have to build it from source code. Don't worry, it's actually pretty
straightforward if you are working on a Unix-like platform. What system are
you working on?
best,
Robert

**Comment by robert-dodier** [comment]
Miguel, I can't tell what's going on, you'll have to provide more information. Ideally you could paste in the error messages verbatim, and also provide more information about the environment. If you have a running Maxima executable (which you built or installed from a package), please also report the output of `build_info();`. Also report anything else that seems relevant.

**Comment by miguelmarco** [comment]
Ok, I tried to do a restart from zero. I did the following:

- Download ccl and installk `ccl` and `ccl64` to `/usr/local/bin`
- Download maxima 5.41 source code
- Inside maxiam directory, run `configure --with-ccl64=ccl64 --enable-ccl64`  (that got me some  executable files, in particular, a file called maxima-local in the current directory)
- Tried to install quicklisp. downloaded it and from a maxima session I did: 
```
(%i1) :lisp (load "quicklisp.lisp")
```
And I got 

```

  ==== quicklisp quickstart 2015-01-28 loaded ====

    To continue with installation, evaluate: (quicklisp-quickstart:install)

    For installation options, evaluate: (quicklisp-quickstart:help)

/home/ubuntu/maxima-5.41.0/quicklisp.lisp
```

So I tried `:lisp (quicklisp-quickstart:install)`

And then I got this message

```

  ==== quicklisp quickstart 2015-01-28 loaded ====

    To continue with installation, evaluate: (quicklisp-quickstart:install)

    For installation options, evaluate: (quicklisp-quickstart:help)

/home/ubuntu/maxima-5.41.0/quicklisp.lisp
(%i1) :lisp (quicklisp-quickstart:install)
; Fetching #<URL "http://beta.quicklisp.org/client/quicklisp.sexp">
; 0.82KB
==================================================
838 bytes in 0.05 seconds (17.45KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/client/2017-03-06/quicklisp.tar">
; 250.00KB
==================================================
256,000 bytes in 0.14 seconds (1733.91KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/client/2015-09-24/setup.lisp">
; 4.94KB
==================================================
5,054 bytes in 0.04 seconds (117.00KB/sec)
; Fetching #<URL "http://beta.quicklisp.org/asdf/2.26/asdf.lisp">
; 194.07KB
==================================================
198,729 bytes in 0.12 seconds (1638.34KB/sec)
Maxima encountered a Lisp error:

 MK:DEFSYSTEM: missing system ASDF.

Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.

```
So I guess I am doing something very wrong.

**Comment by miguelmarco** [comment]
Ok, I finally managed to create a valid maxima image, and it works. I didn't do the codemirror/pygments patching, so I don't have code highlighting, but I can live with that.

However, I have a problem with graphics: they just don't show up in the notebook (I am using jupyterlab through jupyterhub, so that might be the problem)

**Comment by miguelmarco** [comment]
Yes, I tried that and didn¡t work.... but it actually worked using png instead of svg.

**Comment by robert-dodier** [comment]
I'm closing this issue, but if anyone is still having any problem, I encourage them to open a new issue for that.
