### ISSUE TITLE
Binder Error

### ISSUE THREAD

**Issue by rcmlz** [robert-dodier/maxima-jupyter#97]
Hello Robert

currently your Binder Demo

https://mybinder.org/v2/gh/robert-dodier/maxima-jupyter/master?urlpath=lab

fails with

Step 1/13 : FROM archlinux/base:latest
pull access denied for archlinux/base, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

**Comment by yitzchak** [comment]
They changed the name to `archlinux:latest`. It probably isn't worth fixing now, because pacman is currently broke on Docker. Once it starts working on common-lisp-jupyter, I can come back and fix maxima-jupyter.

**Comment by rcmlz** [comment]
Thank you.

**Comment by yitzchak** [comment]
What OS are you on?

**Comment by rcmlz** [comment]
I do teaching, plan to use it via Binder (so OS is would be Linux), distribute my notebooks via git. I suspect that only a simple npm/pip/conda/(+ some apt-get) install procedure will motivate people to do a local install and use Maxima outside class/outside Binder.

**Comment by robert-dodier** [comment]
> I suspect that only a simple npm/pip/conda/(+ some apt-get) install procedure will motivate students to do a local installation and use Maxima-Jupyter outside class/outside Binder. 

Do I understand correctly that what you're getting at is that the complexity of the installation process discourages new users? I think so too -- I'm just trying to understand what you are suggesting here.

**Comment by rcmlz** [comment]
Yes, I like to use Maxima via Jupyter for teaching and believe that a simple installation process - where students can easily make the jupyter-maxima kernel a part of their local installation (side by side with other kernels used, so they can switch inside notebooks) - would be beneficial.

However, IMHO also having the Binder demo up and running is important to be able to showcase anytime.

**Comment by yitzchak** [comment]
I've managed to get common-lisp-jupyter's binder to work, so I'll start on maxima-jupyter's next. Also, please note that there are updated install instructions for those on Windows with conda.

https://github.com/yitzchak/common-lisp-jupyter/wiki/Windows-Installation

**Comment by rcmlz** [comment]
Thank you for your work. I am looking forward to Maxima-Jupyter-Binder beeing up again too.

I started your binder link 

https://mybinder.org/v2/gh/yitzchak/common-lisp-jupyter/master

but got:

Cloning into 'roswell'...
==> ERROR: /etc/makepkg.conf not found.
    Aborting...
